### ISSUE TITLE
Just curious

### ISSUE THREAD

**Issue by flatr0ze** [Jing0/md2html#1]
Great work, but how come you haven't used Sundown or a similar C library to accomplish the Markdown-to-HTML conversion?
Not saying that they're any better, haven't had time to compare... but wanted to know the reason that made you write your own processor from scratch...

**Comment by Jing0** [comment]
Thank you for commenting! 
I knew there are some C libraries that can convert Markdown to HTML, many of which may perform better in speed, for now.
MD2HTML is my first *product* made by my own after four-month learning for C. To be honest,  I just do it for fun :smile:

**Comment by flatr0ze** [comment]
Gotcha.
I'm also learning C right now, got into the web development too much so decided to explore the world of true programming.

It's a nice program, I will use it to convert my CV written in Markdown to HTML and then to PDF via some wkhtmltopdf or similar.

P.S.
I got some interesting projects related to C in my organizations, please let me know if you'd like to work on them together: https://github.com/ZZYZX/apng2mng, https://github.com/ZZYZX/poweriso (and a bunch of filesystem drivers for free OSs here: https://github.com/defiant-labs)

Take care!
